version: "3"
services:
  db:
    image: couchdb:latest
    restart: always
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
  web:
    build: .
    restart: always
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
      - COUCHDB_HOST=db
    ports:
      - "8080:80"
