version: "3"
services:
  db:
    image: couchdb:latest
    restart: always
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - couchdb:/opt/couchdb/data

  varnish:
    image: varnish:latest
    volumes:
      - "./default.vcl:/etc/varnish/default.vcl"
    ports:
      - "8080:80"
    environment:
      - VARNISH_SIZE=2G
    command: -p default_keep=300
    depends_on:
      - web

  web:
    image: nginx:latest
    restart: always
    depends_on:
      - php
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html

  php:
    image: php:8-fpm
    restart: always
    depends_on:
      - composer
    volumes:
      - ./src:/var/www/html
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
      - COUCHDB_HOST=db

  composer:
    image: composer:latest
    command: [ "composer", "install" ]
    volumes:
      - ./src:/app

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  couchdb:
