version: "3"
services:
  db:
    image: couchdb:latest
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - couchdb:/opt/couchdb/data

  varnish:
    image: varnish:latest
    volumes:
      - "./default.vcl:/etc/varnish/default.vcl"
    ports:
      - "8080:80"
    environment:
      - VARNISH_SIZE=2G
    depends_on:
      - php

  php:
    build: .
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
      - COUCHDB_HOST=db

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  couchdb:
